Check stack size is forwarded to PIC correctly

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -668,3 +668,25 @@ jobs:
           mkdir build && cd build
           cmake .. -DBUILD_OPENSSL=TRUE -DBUILD_OPENSSL_PLATFORM=linux-generic32 -DBUILD_LIBSRTP_HOST_PLATFORM=x86_64-unknown-linux-gnu -DBUILD_LIBSRTP_DESTINATION_PLATFORM=arm-unknown-linux-uclibcgnueabi
           make
+
+  Stack-Size-Check:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Clone repository
+        uses: actions/checkout@v3
+      - name: Check StackSize with Invalid Value
+        run: |
+          mkdir build && cd build
+          cmake .. -DKVS_STACK_SIZE=65536asdfsadf
+          if [ $? -eq 0 ]; then
+            echo "CMake unexpectedly succeeded with invalid KVS_STACK_SIZE"
+            exit 1
+          fi
+      - name: Check Stack Size is Set
+        run: |
+          mkdir build && cd build
+          CMAKE_LOGS=$(cmake .. -DKVS_STACK_SIZE=65536 2>&1)
+          if [ ! echo "$CMAKE_LOGS" | grep -q "Building with default stack size: 65536 bytes" ]; then
+            echo "Stack size was not sent to PIC properly."
+            exit 1
+          fi
